BEGIN;
insert into `dexter`.`videos` (id, file_name, group_id, path) values (1, '0001.mp4', 'dexter', 'media/videos/dexter/');
insert into `dexter`.`videos` (id, file_name, group_id, path) values (2, '0002.mp4', 'dexter', 'media/videos/dexter/');
insert into `dexter`.`videos` (id, file_name, group_id, path) values (3, '0003.mp4', 'dexter', 'media/videos/dexter/');
insert into `dexter`.`videos` (id, file_name, group_id, path) values (4, '0004.mp4', 'dexter', 'media/videos/dexter/');
insert into `dexter`.`videos` (id, file_name, group_id, path) values (5, '0005.mp4', 'dexter', 'media/videos/dexter/');
insert into `dexter`.`videos` (id, file_name, group_id, path) values (6, '0006.mp4', 'dexter', 'media/videos/dexter/');
insert into `dexter`.`videos` (id, file_name, group_id, path) values (7, '0007.mp4', 'dexter', 'media/videos/dexter/');
insert into `dexter`.`videos` (id, file_name, group_id, path) values (8, '0008.mp4', 'dexter', 'media/videos/dexter/');
COMMIT;